apiVersion: v1
appVersion: 1.18.9.2578-513b381af
description: Plex Helm Chart
name: plex
version: 1.7.0
icon: https://raw.githubusercontent.com/plexinc/pms-docker/master/img/plex-server.png
maintainer:
- email: flav.hardy@gmail.com
  name: fydrah
keywords:
- plex
- helm
