apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "plex.fullname" . }}
  labels:
    app: {{ template "plex.name" . }}
    chart: {{ template "plex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "plex.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "plex.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ template "plex.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PLEX_UID
              value: "{{ .Values.process.uid }}"
            - name: PLEX_GID
              value: "{{ .Values.process.gid }}"
            - name: ADVERTISE_IP
              value: "{{ .Values.advertiseIP }}"
            - name: PLEX_CLAIM
              value: "{{ .Values.plexClaim }}"
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
            {{- range .Values.service.stream.ports.tcp }}
            - name: {{ .name }}-tcp
              containerPort: {{ .port }}
              protocol: TCP
            {{- end }}
            {{- range .Values.service.stream.ports.udp }}
            - name: {{ .name }}-udp
              containerPort: {{ .port }}
              protocol: UDP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /identity
              port: http
          readinessProbe:
            httpGet:
              path: /identity
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
              readOnly: true
            - mountPath: /transcode
              name: transcode
            - mountPath: /tmp
              name: transcode
      volumes:
      - name: config
      {{- if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.config.existingClaim | default (printf "%s-%s" (include "plex.fullname" .) "config") }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: data
      {{- if .Values.persistence.data.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.data.existingClaim | default (printf "%s-%s" (include "plex.fullname" .) "data") }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: transcode
      {{- if .Values.persistence.transcode.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.transcode.existingClaim | default (printf "%s-%s" (include "plex.fullname" .) "transcode") }}
      {{- else }}
        emptyDir: {}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
