apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
data:
  PLEX_CLAIM: {{ .Values.plexClaim | b64enc | quote }}
  ADVERTISE_IP: {{ .Values.advertiseAddress | b64enc | quote }}
