apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "plex.fullname" . }}
  labels:
    app: {{ template "plex.name" . }}
    chart: {{ template "plex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
