apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
{{- if .Values.service.web.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.web.externalIPs | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range .Values.service.stream.ports.tcp }}
    - name: {{ .name }}-tcp
      targetPort: {{ .name }}-tcp
      protocol: TCP
      port: {{ .port }}
    {{- end }}
    {{- range .Values.service.stream.ports.udp }}
    - name: {{ .name }}-udp
      targetPort: {{ .name }}-udp
      protocol: UDP
      port: {{ .port }}
    {{- end }}
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}
