{{ range .Values.namespaces }}
{{ if .defaultNetworkPolicy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-ingress
  namespace: {{ .name }}
spec:
  podSelector:
    matchLabels:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: {{ .name }}
spec:
  podSelector:
    matchLabels:
  policyTypes:
  - Egress
  egress:
  - {}
{{- end -}}
{{- end -}}
