{{- if and .Values.persistence.watch.enabled (not .Values.persistence.watch.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "..fullname" . }}-watch
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.persistence.watch.labels }}
{{ toYaml .Values.persistence.watch.labels | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.watch.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.watch.size | quote }}
{{- if .Values.persistence.watch.storageClass }}
{{- if (eq "-" .Values.persistence.watch.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.watch.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
