apiVersion: v1
kind: Service
metadata:
  name: {{ template "..fullname" . }}
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webui
      protocol: TCP
      name: webui
  selector:
    app: {{ template "..name" . }}
    release: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "..fullname" . }}-peer
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: peer-tcp
      port: 51413
      targetPort: peer-tcp
      protocol: TCP
    - name: peer-udp
      port: 51413
      targetPort: peer-udp
      protocol: UDP
  selector:
    app: {{ template "..name" . }}
    release: {{ .Release.Name }}
