apiVersion: v1
kind: Service
metadata:
  name: {{ template "..fullname" . }}
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.web.type }}
{{- if .Values.service.web.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.web.externalIPs | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: webui
      protocol: TCP
      name: webui
  selector:
    app: {{ template "..name" . }}
    release: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "..fullname" . }}-peer
  labels:
    app: {{ template "..name" . }}
    chart: {{ template "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.peer.type }}
{{- if .Values.service.peer.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.peer.externalIPs | indent 4 }}
{{- end }}
  ports:
    - name: peer-tcp
      port: {{ .Values.service.peer.ports.tcp }}
      targetPort: peer-tcp
      protocol: TCP
    - name: peer-udp
      port: {{ .Values.service.peer.ports.udp }}
      targetPort: peer-udp
      protocol: UDP
  selector:
    app: {{ template "..name" . }}
    release: {{ .Release.Name }}
